package constants

// General error codes
const (
	ERROR_INTERNAL_SERVER = "INTERNAL_SERVER_ERROR"
	ERROR_INVALID_REQUEST = "INVALID_REQUEST"
	ERROR_UNAUTHORIZED    = "UNAUTHORIZED"
	ERROR_FORBIDDEN       = "FORBIDDEN"
	ERROR_NOT_FOUND       = "NOT_FOUND"
)

// User-related error codes
const (
	ERROR_USER_NOT_FOUND     = "USER_NOT_FOUND"
	ERROR_USER_CREATE_FAILED = "USER_CREATE_FAILED"
	ERROR_USER_UPDATE_FAILED = "USER_UPDATE_FAILED"
	ERROR_USER_DELETE_FAILED = "USER_DELETE_FAILED"
	ERROR_INVALID_USER_ID    = "INVALID_USER_ID"
)

// Patient-related error codes
const (
	ERROR_PATIENT_NOT_FOUND     = "PATIENT_NOT_FOUND"
	ERROR_PATIENT_CREATE_FAILED = "PATIENT_CREATE_FAILED"
	ERROR_PATIENT_UPDATE_FAILED = "PATIENT_UPDATE_FAILED"
	ERROR_PATIENT_DELETE_FAILED = "PATIENT_DELETE_FAILED"
	ERROR_INVALID_PATIENT_ID    = "INVALID_PATIENT_ID"
	ERROR_PATIENT_SEARCH_FAILED = "PATIENT_SEARCH_FAILED"
)

// Appointment-related error codes
const (
	ERROR_APPOINTMENT_NOT_FOUND     = "APPOINTMENT_NOT_FOUND"
	ERROR_APPOINTMENT_CREATE_FAILED = "APPOINTMENT_CREATE_FAILED"
	ERROR_APPOINTMENT_UPDATE_FAILED = "APPOINTMENT_UPDATE_FAILED"
	ERROR_APPOINTMENT_DELETE_FAILED = "APPOINTMENT_DELETE_FAILED"
	ERROR_INVALID_APPOINTMENT_ID    = "INVALID_APPOINTMENT_ID"
)

// Medical record error codes
const (
	ERROR_MEDICAL_HISTORY_NOT_FOUND     = "MEDICAL_HISTORY_NOT_FOUND"
	ERROR_MEDICAL_HISTORY_CREATE_FAILED = "MEDICAL_HISTORY_CREATE_FAILED"
	ERROR_MEDICAL_HISTORY_UPDATE_FAILED = "MEDICAL_HISTORY_UPDATE_FAILED"
	ERROR_MEDICAL_HISTORY_DELETE_FAILED = "MEDICAL_HISTORY_DELETE_FAILED"
	ERROR_INVALID_MEDICAL_HISTORY_ID    = "INVALID_MEDICAL_HISTORY_ID"
	ERROR_DIAGNOSIS_NOT_FOUND           = "DIAGNOSIS_NOT_FOUND"
	ERROR_DIAGNOSIS_CREATE_FAILED       = "DIAGNOSIS_CREATE_FAILED"
	ERROR_DIAGNOSIS_UPDATE_FAILED       = "DIAGNOSIS_UPDATE_FAILED"
	ERROR_DIAGNOSIS_DELETE_FAILED       = "DIAGNOSIS_DELETE_FAILED"
	ERROR_INVALID_DIAGNOSIS_ID          = "INVALID_DIAGNOSIS_ID"
	ERROR_PRESCRIPTION_NOT_FOUND        = "PRESCRIPTION_NOT_FOUND"
	ERROR_PRESCRIPTION_CREATE_FAILED    = "PRESCRIPTION_CREATE_FAILED"
	ERROR_PRESCRIPTION_UPDATE_FAILED    = "PRESCRIPTION_UPDATE_FAILED"
	ERROR_PRESCRIPTION_DELETE_FAILED    = "PRESCRIPTION_DELETE_FAILED"
	ERROR_INVALID_PRESCRIPTION_ID       = "INVALID_PRESCRIPTION_ID"
)

// Additional domain-specific error codes
const (
	ERROR_ALLERGY_NOT_FOUND             = "ALLERGY_NOT_FOUND"
	ERROR_ALLERGY_CREATE_FAILED         = "ALLERGY_CREATE_FAILED"
	ERROR_ALLERGY_UPDATE_FAILED         = "ALLERGY_UPDATE_FAILED"
	ERROR_ALLERGY_DELETE_FAILED         = "ALLERGY_DELETE_FAILED"
	ERROR_INVALID_ALLERGY_ID            = "INVALID_ALLERGY_ID"
	ERROR_VITAL_SIGN_NOT_FOUND          = "VITAL_SIGN_NOT_FOUND"
	ERROR_VITAL_SIGN_CREATE_FAILED      = "VITAL_SIGN_CREATE_FAILED"
	ERROR_VITAL_SIGN_UPDATE_FAILED      = "VITAL_SIGN_UPDATE_FAILED"
	ERROR_VITAL_SIGN_DELETE_FAILED      = "VITAL_SIGN_DELETE_FAILED"
	ERROR_INVALID_VITAL_SIGN_ID         = "INVALID_VITAL_SIGN_ID"
	ERROR_MEDICAL_TEST_NOT_FOUND        = "MEDICAL_TEST_NOT_FOUND"
	ERROR_MEDICAL_TEST_CREATE_FAILED    = "MEDICAL_TEST_CREATE_FAILED"
	ERROR_MEDICAL_TEST_UPDATE_FAILED    = "MEDICAL_TEST_UPDATE_FAILED"
	ERROR_MEDICAL_TEST_DELETE_FAILED    = "MEDICAL_TEST_DELETE_FAILED"
	ERROR_INVALID_MEDICAL_TEST_ID       = "INVALID_MEDICAL_TEST_ID"
	ERROR_SURGERY_HISTORY_NOT_FOUND     = "SURGERY_HISTORY_NOT_FOUND"
	ERROR_SURGERY_HISTORY_CREATE_FAILED = "SURGERY_HISTORY_CREATE_FAILED"
	ERROR_SURGERY_HISTORY_UPDATE_FAILED = "SURGERY_HISTORY_UPDATE_FAILED"
	ERROR_SURGERY_HISTORY_DELETE_FAILED = "SURGERY_HISTORY_DELETE_FAILED"
	ERROR_INVALID_SURGERY_HISTORY_ID    = "INVALID_SURGERY_HISTORY_ID"
	ERROR_NFC_CARD_NOT_FOUND            = "NFC_CARD_NOT_FOUND"
	ERROR_NFC_CARD_CREATE_FAILED        = "NFC_CARD_CREATE_FAILED"
	ERROR_NFC_CARD_UPDATE_FAILED        = "NFC_CARD_UPDATE_FAILED"
	ERROR_NFC_CARD_DELETE_FAILED        = "NFC_CARD_DELETE_FAILED"
	ERROR_INVALID_CARD_ID               = "INVALID_CARD_ID"
	ERROR_CARD_ASSIGN_FAILED            = "CARD_ASSIGN_FAILED"
	ERROR_CARD_DEACTIVATE_FAILED        = "CARD_DEACTIVATE_FAILED"
	ERROR_NFC_AUTHENTICATION_FAILED     = "NFC_AUTHENTICATION_FAILED"
)

// VEM 2.0 Read-Only System error codes
const (
	ERROR_METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
	ERROR_INVALID_DATE_RANGE = "INVALID_DATE_RANGE"
	ERROR_INVALID_KODU       = "INVALID_KODU"
)

// VEM 2.0 Entity-specific error codes
const (
	ERROR_PERSONEL_NOT_FOUND             = "PERSONEL_NOT_FOUND"
	ERROR_INVALID_PERSONEL_KODU          = "INVALID_PERSONEL_KODU"
	ERROR_NFC_KART_NOT_FOUND             = "NFC_KART_NOT_FOUND"
	ERROR_INVALID_NFC_KART_KODU          = "INVALID_NFC_KART_KODU"
	ERROR_HASTA_NOT_FOUND                = "HASTA_NOT_FOUND"
	ERROR_INVALID_HASTA_KODU             = "INVALID_HASTA_KODU"
	ERROR_HASTA_BASVURU_NOT_FOUND        = "HASTA_BASVURU_NOT_FOUND"
	ERROR_INVALID_HASTA_BASVURU_KODU     = "INVALID_HASTA_BASVURU_KODU"
	ERROR_YATAK_NOT_FOUND                = "YATAK_NOT_FOUND"
	ERROR_INVALID_YATAK_KODU             = "INVALID_YATAK_KODU"
	ERROR_TABLET_CIHAZ_NOT_FOUND         = "TABLET_CIHAZ_NOT_FOUND"
	ERROR_INVALID_TABLET_CIHAZ_KODU      = "INVALID_TABLET_CIHAZ_KODU"
	ERROR_ANLIK_YATAN_HASTA_NOT_FOUND    = "ANLIK_YATAN_HASTA_NOT_FOUND"
	ERROR_INVALID_ANLIK_YATAN_HASTA_KODU = "INVALID_ANLIK_YATAN_HASTA_KODU"
	ERROR_VITAL_BULGU_NOT_FOUND          = "VITAL_BULGU_NOT_FOUND"
	ERROR_INVALID_VITAL_BULGU_KODU       = "INVALID_VITAL_BULGU_KODU"
	ERROR_KLINIK_SEYIR_NOT_FOUND         = "KLINIK_SEYIR_NOT_FOUND"
	ERROR_INVALID_KLINIK_SEYIR_KODU      = "INVALID_KLINIK_SEYIR_KODU"
	ERROR_TIBBI_ORDER_NOT_FOUND          = "TIBBI_ORDER_NOT_FOUND"
	ERROR_INVALID_TIBBI_ORDER_KODU       = "INVALID_TIBBI_ORDER_KODU"
	ERROR_TETKIK_SONUC_NOT_FOUND         = "TETKIK_SONUC_NOT_FOUND"
	ERROR_INVALID_TETKIK_SONUC_KODU      = "INVALID_TETKIK_SONUC_KODU"
	ERROR_RECETE_NOT_FOUND               = "RECETE_NOT_FOUND"
	ERROR_INVALID_RECETE_KODU            = "INVALID_RECETE_KODU"
	ERROR_BASVURU_TANI_NOT_FOUND         = "BASVURU_TANI_NOT_FOUND"
	ERROR_INVALID_BASVURU_TANI_KODU      = "INVALID_BASVURU_TANI_KODU"
	ERROR_HASTA_TIBBI_BILGI_NOT_FOUND    = "HASTA_TIBBI_BILGI_NOT_FOUND"
	ERROR_INVALID_HASTA_TIBBI_BILGI_KODU = "INVALID_HASTA_TIBBI_BILGI_KODU"
	ERROR_HASTA_UYARI_NOT_FOUND          = "HASTA_UYARI_NOT_FOUND"
	ERROR_INVALID_HASTA_UYARI_KODU       = "INVALID_HASTA_UYARI_KODU"
	ERROR_RISK_SKORLAMA_NOT_FOUND        = "RISK_SKORLAMA_NOT_FOUND"
	ERROR_INVALID_RISK_SKORLAMA_KODU     = "INVALID_RISK_SKORLAMA_KODU"
	ERROR_BASVURU_YEMEK_NOT_FOUND        = "BASVURU_YEMEK_NOT_FOUND"
	ERROR_INVALID_BASVURU_YEMEK_KODU     = "INVALID_BASVURU_YEMEK_KODU"
)
