package constants

// General success codes
const (
	SUCCESS_OPERATION_COMPLETED = "OPERATION_COMPLETED"
	SUCCESS_DATA_RETRIEVED      = "DATA_RETRIEVED"
)

// User-related success codes
const (
	SUCCESS_USER_CREATED    = "USER_CREATED"
	SUCCESS_USER_RETRIEVED  = "USER_RETRIEVED"
	SUCCESS_USER_UPDATED    = "USER_UPDATED"
	SUCCESS_USER_DELETED    = "USER_DELETED"
	SUCCESS_USERS_RETRIEVED = "USERS_RETRIEVED"
)

// Patient-related success codes
const (
	SUCCESS_PATIENT_CREATED                   = "PATIENT_CREATED"
	SUCCESS_PATIENT_RETRIEVED                 = "PATIENT_RETRIEVED"
	SUCCESS_PATIENT_UPDATED                   = "PATIENT_UPDATED"
	SUCCESS_PATIENT_DELETED                   = "PATIENT_DELETED"
	SUCCESS_PATIENTS_RETRIEVED                = "PATIENTS_RETRIEVED"
	SUCCESS_PATIENT_MEDICAL_HISTORY_RETRIEVED = "PATIENT_MEDICAL_HISTORY_RETRIEVED"
)

// Appointment-related success codes
const (
	SUCCESS_APPOINTMENT_CREATED    = "APPOINTMENT_CREATED"
	SUCCESS_APPOINTMENT_RETRIEVED  = "APPOINTMENT_RETRIEVED"
	SUCCESS_APPOINTMENT_UPDATED    = "APPOINTMENT_UPDATED"
	SUCCESS_APPOINTMENT_DELETED    = "APPOINTMENT_DELETED"
	SUCCESS_APPOINTMENTS_RETRIEVED = "APPOINTMENTS_RETRIEVED"
)

// Medical record success codes
const (
	SUCCESS_MEDICAL_HISTORY_CREATED     = "MEDICAL_HISTORY_CREATED"
	SUCCESS_MEDICAL_HISTORY_RETRIEVED   = "MEDICAL_HISTORY_RETRIEVED"
	SUCCESS_MEDICAL_HISTORY_UPDATED     = "MEDICAL_HISTORY_UPDATED"
	SUCCESS_MEDICAL_HISTORY_DELETED     = "MEDICAL_HISTORY_DELETED"
	SUCCESS_MEDICAL_HISTORIES_RETRIEVED = "MEDICAL_HISTORIES_RETRIEVED"
	SUCCESS_DIAGNOSIS_CREATED           = "DIAGNOSIS_CREATED"
	SUCCESS_DIAGNOSIS_RETRIEVED         = "DIAGNOSIS_RETRIEVED"
	SUCCESS_DIAGNOSIS_UPDATED           = "DIAGNOSIS_UPDATED"
	SUCCESS_DIAGNOSIS_DELETED           = "DIAGNOSIS_DELETED"
	SUCCESS_DIAGNOSES_RETRIEVED         = "DIAGNOSES_RETRIEVED"
	SUCCESS_PRESCRIPTION_CREATED        = "PRESCRIPTION_CREATED"
	SUCCESS_PRESCRIPTION_RETRIEVED      = "PRESCRIPTION_RETRIEVED"
	SUCCESS_PRESCRIPTION_UPDATED        = "PRESCRIPTION_UPDATED"
	SUCCESS_PRESCRIPTION_DELETED        = "PRESCRIPTION_DELETED"
	SUCCESS_PRESCRIPTIONS_RETRIEVED     = "PRESCRIPTIONS_RETRIEVED"
)

// Additional domain-specific success codes
const (
	SUCCESS_ALLERGY_CREATED             = "ALLERGY_CREATED"
	SUCCESS_ALLERGY_RETRIEVED           = "ALLERGY_RETRIEVED"
	SUCCESS_ALLERGY_UPDATED             = "ALLERGY_UPDATED"
	SUCCESS_ALLERGY_DELETED             = "ALLERGY_DELETED"
	SUCCESS_ALLERGIES_RETRIEVED         = "ALLERGIES_RETRIEVED"
	SUCCESS_VITAL_SIGN_CREATED          = "VITAL_SIGN_CREATED"
	SUCCESS_VITAL_SIGN_RETRIEVED        = "VITAL_SIGN_RETRIEVED"
	SUCCESS_VITAL_SIGN_UPDATED          = "VITAL_SIGN_UPDATED"
	SUCCESS_VITAL_SIGN_DELETED          = "VITAL_SIGN_DELETED"
	SUCCESS_VITAL_SIGNS_RETRIEVED       = "VITAL_SIGNS_RETRIEVED"
	SUCCESS_MEDICAL_TEST_CREATED        = "MEDICAL_TEST_CREATED"
	SUCCESS_MEDICAL_TEST_RETRIEVED      = "MEDICAL_TEST_RETRIEVED"
	SUCCESS_MEDICAL_TEST_UPDATED        = "MEDICAL_TEST_UPDATED"
	SUCCESS_MEDICAL_TEST_DELETED        = "MEDICAL_TEST_DELETED"
	SUCCESS_MEDICAL_TESTS_RETRIEVED     = "MEDICAL_TESTS_RETRIEVED"
	SUCCESS_SURGERY_HISTORY_CREATED     = "SURGERY_HISTORY_CREATED"
	SUCCESS_SURGERY_HISTORY_RETRIEVED   = "SURGERY_HISTORY_RETRIEVED"
	SUCCESS_SURGERY_HISTORY_UPDATED     = "SURGERY_HISTORY_UPDATED"
	SUCCESS_SURGERY_HISTORY_DELETED     = "SURGERY_HISTORY_DELETED"
	SUCCESS_SURGERY_HISTORIES_RETRIEVED = "SURGERY_HISTORIES_RETRIEVED"
	SUCCESS_NFC_CARD_CREATED            = "NFC_CARD_CREATED"
	SUCCESS_NFC_CARD_RETRIEVED          = "NFC_CARD_RETRIEVED"
	SUCCESS_NFC_CARD_UPDATED            = "NFC_CARD_UPDATED"
	SUCCESS_NFC_CARD_DELETED            = "NFC_CARD_DELETED"
	SUCCESS_NFC_CARDS_RETRIEVED         = "NFC_CARDS_RETRIEVED"
	SUCCESS_CARD_ASSIGNED               = "CARD_ASSIGNED"
	SUCCESS_CARD_DEACTIVATED            = "CARD_DEACTIVATED"
	SUCCESS_NFC_AUTHENTICATION          = "NFC_AUTHENTICATION_SUCCESSFUL"
)

// VEM 2.0 Entity-specific success codes
const (
	SUCCESS_PERSONEL_RETRIEVED             = "PERSONEL_RETRIEVED"
	SUCCESS_PERSONELLER_RETRIEVED          = "PERSONELLER_RETRIEVED"
	SUCCESS_NFC_KART_RETRIEVED             = "NFC_KART_RETRIEVED"
	SUCCESS_NFC_KARTLAR_RETRIEVED          = "NFC_KARTLAR_RETRIEVED"
	SUCCESS_HASTA_RETRIEVED                = "HASTA_RETRIEVED"
	SUCCESS_HASTALAR_RETRIEVED             = "HASTALAR_RETRIEVED"
	SUCCESS_HASTA_BASVURU_RETRIEVED        = "HASTA_BASVURU_RETRIEVED"
	SUCCESS_HASTA_BASVURULAR_RETRIEVED     = "HASTA_BASVURULAR_RETRIEVED"
	SUCCESS_YATAK_RETRIEVED                = "YATAK_RETRIEVED"
	SUCCESS_YATAKLAR_RETRIEVED             = "YATAKLAR_RETRIEVED"
	SUCCESS_TABLET_CIHAZ_RETRIEVED         = "TABLET_CIHAZ_RETRIEVED"
	SUCCESS_TABLET_CIHAZLAR_RETRIEVED      = "TABLET_CIHAZLAR_RETRIEVED"
	SUCCESS_ANLIK_YATAN_HASTA_RETRIEVED    = "ANLIK_YATAN_HASTA_RETRIEVED"
	SUCCESS_ANLIK_YATAN_HASTALAR_RETRIEVED = "ANLIK_YATAN_HASTALAR_RETRIEVED"
	SUCCESS_VITAL_BULGU_RETRIEVED          = "VITAL_BULGU_RETRIEVED"
	SUCCESS_VITAL_BULGULAR_RETRIEVED       = "VITAL_BULGULAR_RETRIEVED"
	SUCCESS_KLINIK_SEYIR_RETRIEVED         = "KLINIK_SEYIR_RETRIEVED"
	SUCCESS_KLINIK_SEYIRLER_RETRIEVED      = "KLINIK_SEYIRLER_RETRIEVED"
	SUCCESS_TIBBI_ORDER_RETRIEVED          = "TIBBI_ORDER_RETRIEVED"
	SUCCESS_TIBBI_ORDERLAR_RETRIEVED       = "TIBBI_ORDERLAR_RETRIEVED"
	SUCCESS_TIBBI_ORDER_DETAY_RETRIEVED    = "TIBBI_ORDER_DETAY_RETRIEVED"
	SUCCESS_TETKIK_SONUC_RETRIEVED         = "TETKIK_SONUC_RETRIEVED"
	SUCCESS_TETKIK_SONUCLAR_RETRIEVED      = "TETKIK_SONUCLAR_RETRIEVED"
	SUCCESS_RECETE_RETRIEVED               = "RECETE_RETRIEVED"
	SUCCESS_RECETELER_RETRIEVED            = "RECETELER_RETRIEVED"
	SUCCESS_RECETE_ILACLAR_RETRIEVED       = "RECETE_ILACLAR_RETRIEVED"
	SUCCESS_BASVURU_TANI_RETRIEVED         = "BASVURU_TANI_RETRIEVED"
	SUCCESS_BASVURU_TANILAR_RETRIEVED      = "BASVURU_TANILAR_RETRIEVED"
	SUCCESS_HASTA_TIBBI_BILGI_RETRIEVED    = "HASTA_TIBBI_BILGI_RETRIEVED"
	SUCCESS_HASTA_TIBBI_BILGILER_RETRIEVED = "HASTA_TIBBI_BILGILER_RETRIEVED"
	SUCCESS_HASTA_UYARI_RETRIEVED          = "HASTA_UYARI_RETRIEVED"
	SUCCESS_HASTA_UYARILAR_RETRIEVED       = "HASTA_UYARILAR_RETRIEVED"
	SUCCESS_RISK_SKORLAMA_RETRIEVED        = "RISK_SKORLAMA_RETRIEVED"
	SUCCESS_RISK_SKORLAMALAR_RETRIEVED     = "RISK_SKORLAMALAR_RETRIEVED"
	SUCCESS_BASVURU_YEMEK_RETRIEVED        = "BASVURU_YEMEK_RETRIEVED"
	SUCCESS_BASVURU_YEMEKLER_RETRIEVED     = "BASVURU_YEMEKLER_RETRIEVED"
)
