import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    dropdownBtn: {
    borderWidth: 1,
    width: '100%',
    height: 50,
    borderRadius: 10,
    borderColor: '#d2d9dfff',
    justifyContent: 'center',
    marginTop: 10,
    padding: 10,
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropwdownText: {
    fontSize: 20,
    fontWeight: '500',
  },
  dropdownContent: {
    padding: 12,
    backgroundColor: '#f5f5f5',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  appointmentItem: {
    padding: 8,
    height: 80,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d2d9dfff',
    shadowColor: '#6d6d6dff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 1,
    gap: 8,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  appointmentStatus: {
    backgroundColor: '#dcfce7',
    padding: 4,
    height:30,
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    borderRadius: 12,
    minHeight:5
  },
  statusText: {
    color: '#166534',
  },
  appointmentTitle: {
    fontSize: 16,
    fontWeight: '500',
  },
  appointmentDate: {
    fontSize: 14,
    color: '#6b7280',
  },
  appointmentInfo: {
    flex: 1,
    justifyContent: 'space-around',
  },
  appointmentDoctor: {
    fontSize: 12,
    color: '#888',
    marginTop: 2,
  },
  noDataText: {
    textAlign: 'center',
    padding: 20,
    color: '#666',
    fontSize: 14,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 20,
    width: '80%',
    height: '60%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#d6d1d1ff',
    paddingBottom: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    flex: 1,
  },
  modalBody: {
    gap: 15,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  detailLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    flex: 1,
  },
  detailValue: {
    fontSize: 14,
    color: '#333',
    flex: 2,
    textAlign: 'right',
  },
  image: {
    width: '100%',
    height: 450,
    borderRadius: 8,
    marginTop: 10,
    resizeMode: 'contain',
  },
  table: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    marginTop: 10,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f8f9fa',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  tableCell: {
    flex: 1,
    fontSize: 12,
    color: '#333',
  },
  tableCellHeader: {
    flex: 1,
    fontSize: 12,
    fontWeight: 'bold',
    color: '#333',
  },
  statusNormal: {
    color: '#16a34a',
    fontWeight: 'bold',
  },
  statusHigh: {
    color: '#dc2626',
    fontWeight: 'bold',
  },
  statusLow: {
    color: '#ea580c',
    fontWeight: 'bold',
  },
});
