package constants

// General success codes
const (
	SUCCESS_OPERATION_COMPLETED = "OPERATION_COMPLETED"
	SUCCESS_DATA_RETRIEVED      = "DATA_RETRIEVED"
)

// User-related success codes
const (
	SUCCESS_USER_CREATED    = "USER_CREATED"
	SUCCESS_USER_RETRIEVED  = "USER_RETRIEVED"
	SUCCESS_USER_UPDATED    = "USER_UPDATED"
	SUCCESS_USER_DELETED    = "USER_DELETED"
	SUCCESS_USERS_RETRIEVED = "USERS_RETRIEVED"
)

// Patient-related success codes
const (
	SUCCESS_PATIENT_CREATED                   = "PATIENT_CREATED"
	SUCCESS_PATIENT_RETRIEVED                 = "PATIENT_RETRIEVED"
	SUCCESS_PATIENT_UPDATED                   = "PATIENT_UPDATED"
	SUCCESS_PATIENT_DELETED                   = "PATIENT_DELETED"
	SUCCESS_PATIENTS_RETRIEVED                = "PATIENTS_RETRIEVED"
	SUCCESS_PATIENT_MEDICAL_HISTORY_RETRIEVED = "PATIENT_MEDICAL_HISTORY_RETRIEVED"
)

// Appointment-related success codes
const (
	SUCCESS_APPOINTMENT_CREATED    = "APPOINTMENT_CREATED"
	SUCCESS_APPOINTMENT_RETRIEVED  = "APPOINTMENT_RETRIEVED"
	SUCCESS_APPOINTMENT_UPDATED    = "APPOINTMENT_UPDATED"
	SUCCESS_APPOINTMENT_DELETED    = "APPOINTMENT_DELETED"
	SUCCESS_APPOINTMENTS_RETRIEVED = "APPOINTMENTS_RETRIEVED"
)

// Medical record success codes
const (
	SUCCESS_MEDICAL_HISTORY_CREATED     = "MEDICAL_HISTORY_CREATED"
	SUCCESS_MEDICAL_HISTORY_RETRIEVED   = "MEDICAL_HISTORY_RETRIEVED"
	SUCCESS_MEDICAL_HISTORY_UPDATED     = "MEDICAL_HISTORY_UPDATED"
	SUCCESS_MEDICAL_HISTORY_DELETED     = "MEDICAL_HISTORY_DELETED"
	SUCCESS_MEDICAL_HISTORIES_RETRIEVED = "MEDICAL_HISTORIES_RETRIEVED"
	SUCCESS_DIAGNOSIS_CREATED           = "DIAGNOSIS_CREATED"
	SUCCESS_DIAGNOSIS_RETRIEVED         = "DIAGNOSIS_RETRIEVED"
	SUCCESS_DIAGNOSIS_UPDATED           = "DIAGNOSIS_UPDATED"
	SUCCESS_DIAGNOSIS_DELETED           = "DIAGNOSIS_DELETED"
	SUCCESS_DIAGNOSES_RETRIEVED         = "DIAGNOSES_RETRIEVED"
	SUCCESS_PRESCRIPTION_CREATED        = "PRESCRIPTION_CREATED"
	SUCCESS_PRESCRIPTION_RETRIEVED      = "PRESCRIPTION_RETRIEVED"
	SUCCESS_PRESCRIPTION_UPDATED        = "PRESCRIPTION_UPDATED"
	SUCCESS_PRESCRIPTION_DELETED        = "PRESCRIPTION_DELETED"
	SUCCESS_PRESCRIPTIONS_RETRIEVED     = "PRESCRIPTIONS_RETRIEVED"
)

// Additional domain-specific success codes
const (
	SUCCESS_ALLERGY_CREATED             = "ALLERGY_CREATED"
	SUCCESS_ALLERGY_RETRIEVED           = "ALLERGY_RETRIEVED"
	SUCCESS_ALLERGY_UPDATED             = "ALLERGY_UPDATED"
	SUCCESS_ALLERGY_DELETED             = "ALLERGY_DELETED"
	SUCCESS_ALLERGIES_RETRIEVED         = "ALLERGIES_RETRIEVED"
	SUCCESS_VITAL_SIGN_CREATED          = "VITAL_SIGN_CREATED"
	SUCCESS_VITAL_SIGN_RETRIEVED        = "VITAL_SIGN_RETRIEVED"
	SUCCESS_VITAL_SIGN_UPDATED          = "VITAL_SIGN_UPDATED"
	SUCCESS_VITAL_SIGN_DELETED          = "VITAL_SIGN_DELETED"
	SUCCESS_VITAL_SIGNS_RETRIEVED       = "VITAL_SIGNS_RETRIEVED"
	SUCCESS_MEDICAL_TEST_CREATED        = "MEDICAL_TEST_CREATED"
	SUCCESS_MEDICAL_TEST_RETRIEVED      = "MEDICAL_TEST_RETRIEVED"
	SUCCESS_MEDICAL_TEST_UPDATED        = "MEDICAL_TEST_UPDATED"
	SUCCESS_MEDICAL_TEST_DELETED        = "MEDICAL_TEST_DELETED"
	SUCCESS_MEDICAL_TESTS_RETRIEVED     = "MEDICAL_TESTS_RETRIEVED"
	SUCCESS_SURGERY_HISTORY_CREATED     = "SURGERY_HISTORY_CREATED"
	SUCCESS_SURGERY_HISTORY_RETRIEVED   = "SURGERY_HISTORY_RETRIEVED"
	SUCCESS_SURGERY_HISTORY_UPDATED     = "SURGERY_HISTORY_UPDATED"
	SUCCESS_SURGERY_HISTORY_DELETED     = "SURGERY_HISTORY_DELETED"
	SUCCESS_SURGERY_HISTORIES_RETRIEVED = "SURGERY_HISTORIES_RETRIEVED"
	SUCCESS_NFC_CARD_CREATED            = "NFC_CARD_CREATED"
	SUCCESS_NFC_CARD_RETRIEVED          = "NFC_CARD_RETRIEVED"
	SUCCESS_NFC_CARD_UPDATED            = "NFC_CARD_UPDATED"
	SUCCESS_NFC_CARD_DELETED            = "NFC_CARD_DELETED"
	SUCCESS_NFC_CARDS_RETRIEVED         = "NFC_CARDS_RETRIEVED"
	SUCCESS_CARD_ASSIGNED               = "CARD_ASSIGNED"
	SUCCESS_CARD_DEACTIVATED            = "CARD_DEACTIVATED"
	SUCCESS_NFC_AUTHENTICATION          = "NFC_AUTHENTICATION_SUCCESSFUL"
)
